# Generated by Django 4.0.3 on 2022-05-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Slider',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='slider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wanderingapp.slider'),
        ),
    ]
