# Generated by Django 3.2.7 on 2022-02-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
