# Generated by Django 4.0.3 on 2022-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0002_sliderimage_rename_post_slider_delete_postimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['image_order']},
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='image_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
