# Generated by Django 4.0.3 on 2022-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0003_alter_sliderimage_options_sliderimage_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['image_order']},
        ),
        migrations.AddField(
            model_name='slider',
            name='image_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
