# Generated by Django 4.0.3 on 2022-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0004_alter_slider_options_slider_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
