# Generated by Django 4.0.3 on 2022-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0005_alter_slider_image_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
