# Generated by Django 4.0.3 on 2022-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0006_slider_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
