# Generated by Django 4.0.3 on 2022-06-15 08:21

from django.db import migrations, models
import wanderingproject.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('wanderingapp', '0007_remove_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='images',
            field=models.FileField(storage=wanderingproject.storage_backends.MediaStorage, upload_to=''),
        ),
    ]
